# Generated by Django 4.2.3 on 2023-07-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='test', upload_to='pics'),
            preserve_default=False,
        ),
    ]
